# Generated by Django 4.2.2 on 2023-07-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=200)),
                ("ip", models.CharField(max_length=200)),
                ("root_user", models.CharField(max_length=200)),
                ("root_pass", models.CharField(max_length=200)),
                ("email_port", models.CharField(max_length=200)),
                ("email_user", models.CharField(max_length=200)),
                ("email_password", models.CharField(max_length=200)),
                ("fromemail", models.CharField(max_length=200)),
                ("some_notes", models.CharField(max_length=200)),
            ],
        ),
    ]
