# Generated by Django 4.2.2 on 2023-07-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
