# Generated by Django 4.2.2 on 2023-07-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_server_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
